import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedMarcaWidget5.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedRectangle24Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedRectangle32Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedRectangle26Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedSinalderede1Widget10.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/Generated1742Widget10.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedLine7Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedSelecionesuamotocicletaWidget2.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedSetadireita1Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedMoto1Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedBateriacheia1Widget10.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedEllipse28Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget1/generated/GeneratedWifi1Widget10.dart';

/* Frame Motocycle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMotocycleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 90.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 328.0,
            child: GeneratedRectangle24Widget4(),
          ),
          Positioned(
            left: 0.0,
            top: 473.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 85.0,
            child: GeneratedRectangle26Widget5(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 89.0,
            child: GeneratedRectangle27Widget1(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget10(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget10(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget10(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget10(),
          ),
          Positioned(
            left: 0.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget5(),
          ),
          Positioned(
            left: 70.0,
            top: 425.0,
            right: null,
            bottom: null,
            width: 243.0,
            height: 29.0,
            child: GeneratedSelecionesuamotocicletaWidget2(),
          ),
          Positioned(
            left: 25.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 37.0,
            child: GeneratedMoto1Widget2(),
          ),
          Positioned(
            left: 26.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget5(),
          ),
          Positioned(
            left: 335.6816711425781,
            top: 499.5697021484375,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget5(),
          ),
          Positioned(
            left: -1984.0,
            top: -988.0,
            right: null,
            bottom: null,
            width: 181.0,
            height: 181.0,
            child: GeneratedEllipse28Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 558.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 1.0,
            child: GeneratedLine7Widget3(),
          ),
          Positioned(
            left: 40.04071044921875,
            top: 80.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget5(),
          )
        ]),
      ),
    ));
  }
}
