import 'package:flutter/material.dart';

/* Rectangle 1000_F_280874872_tVNxGcKAMB3s1rVuNtcB8MeloTb0PV28 (1) 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated1000_F_280874872_tVNxGcKAMB3s1rVuNtcB8MeloTb0PV2811Widg
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 999.0,
        height: 1000.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/c093fdec5115845b8325f364d655112b30ad24c9.png",
            color: null,
            fit: BoxFit.cover,
            width: 999.0,
            height: 1000.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
