import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/Generated1742Widget9.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedMarcaWidget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedShinerayWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedLine8Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedLine7Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedSinalderede1Widget9.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedSetadireita1Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedBateriacheia1Widget9.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle26Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedWifi1Widget9.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedMoto1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle32Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedElektraWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedVoltzWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedSelecionesuamotocicletaWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedmotocyclewidget/generated/GeneratedRectangle44Widget.dart';

/* Frame Motocycle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMotocycleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 90.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 328.0,
            child: GeneratedRectangle24Widget3(),
          ),
          Positioned(
            left: 0.0,
            top: 473.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 342.0,
            child: GeneratedRectangle26Widget4(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 89.0,
            child: GeneratedRectangle27Widget(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget9(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget9(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget9(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget9(),
          ),
          Positioned(
            left: 0.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget4(),
          ),
          Positioned(
            left: 70.0,
            top: 425.0,
            right: null,
            bottom: null,
            width: 243.0,
            height: 29.0,
            child: GeneratedSelecionesuamotocicletaWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 37.0,
            child: GeneratedMoto1Widget1(),
          ),
          Positioned(
            left: 26.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget4(),
          ),
          Positioned(
            left: 25.0,
            top: 586.0,
            right: null,
            bottom: null,
            width: 71.0,
            height: 32.0,
            child: GeneratedVoltzWidget(),
          ),
          Positioned(
            left: 367.9990234375,
            top: 531.2391357421875,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget4(),
          ),
          Positioned(
            left: 0.0,
            top: 558.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 1.0,
            child: GeneratedLine7Widget2(),
          ),
          Positioned(
            left: 26.0,
            top: 641.0,
            right: null,
            bottom: null,
            width: 93.0,
            height: 32.0,
            child: GeneratedElektraWidget(),
          ),
          Positioned(
            left: 26.0,
            top: 696.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 32.0,
            child: GeneratedShinerayWidget(),
          ),
          Positioned(
            left: 128.0,
            top: 643.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle42Widget1(),
          ),
          Positioned(
            left: 147.0,
            top: 698.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle43Widget1(),
          ),
          Positioned(
            left: 120.0,
            top: 588.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle44Widget(),
          ),
          Positioned(
            left: 120.0,
            top: 589.0,
            right: null,
            bottom: null,
            width: 31.11269760131836,
            height: 1.0,
            child: GeneratedLine8Widget1(),
          ),
          Positioned(
            left: 142.5,
            top: 589.0,
            right: null,
            bottom: null,
            width: 30.4138126373291,
            height: 0.0,
            child: GeneratedLine9Widget1(),
          ),
          Positioned(
            left: 40.04071044921875,
            top: 80.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget4(),
          )
        ]),
      ),
    ));
  }
}
