import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedSetadireita1Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedPreenchimentodevagoesdevistafrontal11Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/Generated1742Widget7.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedVolvoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedWifi1Widget7.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedBmwWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedSelecioneseuveculoWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedRectangle32Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedBateriacheia1Widget7.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedMarcaWidget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedSinalderede1Widget7.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget1/generated/GeneratedVolksvagenWidget.dart';

/* Frame Car 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 328.0,
            child: GeneratedRectangle24Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 344.0,
            child: GeneratedRectangle26Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget2(),
          ),
          Positioned(
            left: 35.0,
            top: 503.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget2(),
          ),
          Positioned(
            left: 35.0,
            top: 586.0,
            right: null,
            bottom: null,
            width: 59.0,
            height: 32.0,
            child: GeneratedBmwWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 646.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 32.0,
            child: GeneratedVolvoWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 700.0,
            right: null,
            bottom: null,
            width: 143.0,
            height: 32.0,
            child: GeneratedVolksvagenWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 89.0,
            child: GeneratedRectangle31Widget1(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget7(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget7(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget7(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget7(),
          ),
          Positioned(
            left: 47.0406494140625,
            top: 79.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget2(),
          ),
          Positioned(
            left: 25.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 39.0,
            child: GeneratedPreenchimentodevagoesdevistafrontal11Widget1(),
          ),
          Positioned(
            left: 75.0,
            top: 426.0,
            right: null,
            bottom: null,
            width: 200.0,
            height: 29.0,
            child: GeneratedSelecioneseuveculoWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 557.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 1.0,
            child: GeneratedLine7Widget(),
          ),
          Positioned(
            left: 143.0,
            top: 588.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle41Widget(),
          ),
          Positioned(
            left: 143.0,
            top: 648.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle42Widget(),
          ),
          Positioned(
            left: 197.0,
            top: 700.0,
            right: null,
            bottom: null,
            width: 23.0,
            height: 23.0,
            child: GeneratedRectangle43Widget(),
          ),
          Positioned(
            left: 367.9991455078125,
            top: 533.2391357421875,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget2(),
          ),
          Positioned(
            left: 143.0,
            top: 589.0,
            right: null,
            bottom: null,
            width: 31.11269760131836,
            height: 1.0,
            child: GeneratedLine8Widget(),
          ),
          Positioned(
            left: 165.5,
            top: 589.0,
            right: null,
            bottom: null,
            width: 30.4138126373291,
            height: 0.0,
            child: GeneratedLine9Widget(),
          )
        ]),
      ),
    ));
  }
}
