import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedSinalderede1Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedLupa1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedConfiguraesWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedSobreWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedEngrenagem1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedBuscarpostosWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedBateriacheia1Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedWifi1Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedPostosfavoritosWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/Generated1742Widget5.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedXWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedFavorito1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedRota1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedTraarrotasWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedOpaVocaindanofezloginnoLoadStopFaaagoraWidget.dart';
import 'package:flutterapp/testeloadapp/generatedmenuwidget/generated/GeneratedInformacoes1Widget.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: -17.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 107.0,
            child: GeneratedRectangle23Widget1(),
          ),
          Positioned(
            left: 348.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget5(),
          ),
          Positioned(
            left: 299.0,
            top: 18.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget5(),
          ),
          Positioned(
            left: 40.0,
            top: 22.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget5(),
          ),
          Positioned(
            left: 98.0,
            top: 18.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget5(),
          ),
          Positioned(
            left: 16.0,
            top: 115.0,
            right: null,
            bottom: null,
            width: 362.0,
            height: 713.0,
            child: GeneratedRectangle38Widget1(),
          ),
          Positioned(
            left: 64.0,
            top: 155.0,
            right: null,
            bottom: null,
            width: 266.0,
            height: 72.0,
            child: GeneratedGroup11Widget1(),
          ),
          Positioned(
            left: 88.0,
            top: 311.0,
            right: null,
            bottom: null,
            width: 2.0,
            height: 16.0,
            child: GeneratedTextWidget(),
          ),
          Positioned(
            left: 64.0,
            top: 254.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 32.0,
            child: GeneratedOpaVocaindanofezloginnoLoadStopFaaagoraWidget(),
          ),
          Positioned(
            left: 130.0,
            top: 296.0,
            right: null,
            bottom: null,
            width: 124.0,
            height: 35.0,
            child: GeneratedRectangle40Widget(),
          ),
          Positioned(
            left: 168.0,
            top: 304.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 23.0,
            child: GeneratedLoginWidget1(),
          ),
          Positioned(
            left: 17.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 361.0,
            height: 1.0,
            child: GeneratedLine6Widget(),
          ),
          Positioned(
            left: 341.0,
            top: 128.0,
            right: null,
            bottom: null,
            width: 18.0,
            height: 32.0,
            child: GeneratedXWidget(),
          ),
          Positioned(
            left: 47.0,
            top: 400.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedRota1Widget(),
          ),
          Positioned(
            left: 47.0,
            top: 459.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedLupa1Widget(),
          ),
          Positioned(
            left: 49.0,
            top: 636.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: GeneratedInformacoes1Widget(),
          ),
          Positioned(
            left: 49.0,
            top: 577.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedEngrenagem1Widget(),
          ),
          Positioned(
            left: 49.0,
            top: 518.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedFavorito1Widget(),
          ),
          Positioned(
            left: 105.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 127.0,
            height: 22.0,
            child: GeneratedBuscarpostosWidget(),
          ),
          Positioned(
            left: 105.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 118.0,
            height: 22.0,
            child: GeneratedTraarrotasWidget(),
          ),
          Positioned(
            left: 105.0,
            top: 524.0,
            right: null,
            bottom: null,
            width: 152.0,
            height: 22.0,
            child: GeneratedPostosfavoritosWidget(),
          ),
          Positioned(
            left: 105.0,
            top: 583.0,
            right: null,
            bottom: null,
            width: 135.0,
            height: 25.0,
            child: GeneratedConfiguraesWidget(),
          ),
          Positioned(
            left: 105.0,
            top: 641.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 25.0,
            child: GeneratedSobreWidget(),
          )
        ]),
      ),
    ));
  }
}
