import 'package:flutter/material.dart';

/* Rectangle Conector de Carro Eletrico - Tipo 2 - IEC 62196 - CCS2 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConectordeCarroEletricoTipo2IEC62196CCS21Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 1215.0,
        height: 350.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/ef285c3a2e57fd0c174d25a895a537cebd625e8d.png",
            color: null,
            fit: BoxFit.cover,
            width: 1215.0,
            height: 350.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
