import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedBateriacheia1Widget6.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/Generated1742Widget6.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedSinalderede1Widget6.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedSelecionesuamotocicletaWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedFiltroWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedMoto1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedDevolta1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedWifi1Widget6.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedSelecioneseuveculoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedMarcaWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedMarcaWidget.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget/generated/GeneratedPreenchimentodevagoesdevistafrontal11Widget.dart';

/* Frame Car 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 85.0,
            child: GeneratedRectangle26Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 196.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 293.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget(),
          ),
          Positioned(
            left: 333.0,
            top: 291.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 89.0,
            child: GeneratedRectangle31Widget(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget6(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget6(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget6(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget6(),
          ),
          Positioned(
            left: 22.0,
            top: 210.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 39.0,
            child: GeneratedPreenchimentodevagoesdevistafrontal11Widget(),
          ),
          Positioned(
            left: 75.0,
            top: 216.0,
            right: null,
            bottom: null,
            width: 200.0,
            height: 29.0,
            child: GeneratedSelecioneseuveculoWidget(),
          ),
          Positioned(
            left: 153.0,
            top: 129.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 32.0,
            child: GeneratedFiltroWidget(),
          ),
          Positioned(
            left: -2.0,
            top: 417.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 85.0,
            child: GeneratedRectangle26Widget1(),
          ),
          Positioned(
            left: 330.0,
            top: 437.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget1(),
          ),
          Positioned(
            left: -2.0,
            top: 349.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget1(),
          ),
          Positioned(
            left: 68.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 243.0,
            height: 29.0,
            child: GeneratedSelecionesuamotocicletaWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 445.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget1(),
          ),
          Positioned(
            left: 16.0,
            top: 367.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 37.0,
            child: GeneratedMoto1Widget(),
          ),
          Positioned(
            left: 28.0,
            top: 126.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedDevolta1Widget1(),
          )
        ]),
      ),
    ));
  }
}
