import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDcccs2Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedEmUsoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedConectoresWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedHistricoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedInformaoWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedIec62196Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedBateriacheia1Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedCharger2Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedIec62196Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDC\$027MINWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedEvgoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedSetadireita1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDcccs2Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/Generated1742Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDevolta1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedGroup10Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedAc\$003MINWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedWifi1Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedNeoenergiaWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDC\$000MINWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedConectoresWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedInformaoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedSinalderede1Widget4.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedHistricoWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedEllipse26Widget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedCharger1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedDisponivelWidget.dart';
import 'package:flutterapp/testeloadapp/generatedchargerwidget/generated/GeneratedAc\$000MINWidget.dart';

/* Frame Charger 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChargerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 17.0,
            top: 148.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 291.0,
            child: GeneratedRectangle21Widget(),
          ),
          Positioned(
            left: 0.0,
            top: -17.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 107.0,
            child: GeneratedRectangle23Widget(),
          ),
          Positioned(
            left: 122.0,
            top: 99.0,
            right: null,
            bottom: null,
            width: 166.0,
            height: 43.0,
            child: GeneratedCharger1Widget1(),
          ),
          Positioned(
            left: 115.0,
            top: 456.0,
            right: null,
            bottom: null,
            width: 166.0,
            height: 43.0,
            child: GeneratedCharger2Widget1(),
          ),
          Positioned(
            left: 348.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget4(),
          ),
          Positioned(
            left: 299.0,
            top: 18.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget4(),
          ),
          Positioned(
            left: 40.0,
            top: 22.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget4(),
          ),
          Positioned(
            left: 98.0,
            top: 18.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget4(),
          ),
          Positioned(
            left: 41.0,
            top: 165.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse21Widget(),
          ),
          Positioned(
            left: 78.0,
            top: 168.0,
            right: null,
            bottom: null,
            width: 79.0,
            height: 24.0,
            child: GeneratedDisponivelWidget(),
          ),
          Positioned(
            left: 17.0,
            top: 211.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 1.0,
            child: GeneratedLine2Widget(),
          ),
          Positioned(
            left: 17.0,
            top: 304.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 1.0,
            child: GeneratedLine3Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 226.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 24.0,
            child: GeneratedNeoenergiaWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 311.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 24.0,
            child: GeneratedConectoresWidget(),
          ),
          Positioned(
            left: 278.0,
            top: 228.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 21.0,
            child: GeneratedInformaoWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 259.0,
            right: null,
            bottom: null,
            width: 86.0,
            height: 18.0,
            child: GeneratedDC$000MINWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 276.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 18.0,
            child: GeneratedAc$000MINWidget(),
          ),
          Positioned(
            left: 99.0,
            top: 348.0,
            right: null,
            bottom: null,
            width: 61.0,
            height: 18.0,
            child: GeneratedIec62196Widget(),
          ),
          Positioned(
            left: 99.0,
            top: 395.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 18.0,
            child: GeneratedDcccs2Widget(),
          ),
          Positioned(
            left: 278.0,
            top: 169.0,
            right: null,
            bottom: null,
            width: 71.0,
            height: 21.0,
            child: GeneratedHistricoWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 340.0,
            right: null,
            bottom: null,
            width: 43.5,
            height: 37.22047424316406,
            child: GeneratedGroup7Widget(),
          ),
          Positioned(
            left: 48.0,
            top: 388.0,
            right: null,
            bottom: null,
            width: 30.2312068939209,
            height: 41.357120513916016,
            child: GeneratedGroup8Widget(),
          ),
          Positioned(
            left: 17.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 291.0,
            child: GeneratedRectangle24Widget(),
          ),
          Positioned(
            left: 78.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 21.0,
            child: GeneratedEmUsoWidget(),
          ),
          Positioned(
            left: 17.0,
            top: 580.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 1.0,
            child: GeneratedLine4Widget(),
          ),
          Positioned(
            left: 17.0,
            top: 673.0,
            right: null,
            bottom: null,
            width: 359.0,
            height: 1.0,
            child: GeneratedLine5Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 595.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 24.0,
            child: GeneratedEvgoWidget(),
          ),
          Positioned(
            left: 34.0,
            top: 678.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 24.0,
            child: GeneratedConectoresWidget1(),
          ),
          Positioned(
            left: 278.0,
            top: 597.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 21.0,
            child: GeneratedInformaoWidget1(),
          ),
          Positioned(
            left: 40.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 86.0,
            height: 18.0,
            child: GeneratedDC$027MINWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 645.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 18.0,
            child: GeneratedAc$003MINWidget(),
          ),
          Positioned(
            left: 99.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 61.0,
            height: 18.0,
            child: GeneratedIec62196Widget1(),
          ),
          Positioned(
            left: 99.0,
            top: 764.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 18.0,
            child: GeneratedDcccs2Widget1(),
          ),
          Positioned(
            left: 279.0,
            top: 541.0,
            right: null,
            bottom: null,
            width: 71.0,
            height: 21.0,
            child: GeneratedHistricoWidget1(),
          ),
          Positioned(
            left: 40.0,
            top: 709.0,
            right: null,
            bottom: null,
            width: 43.5,
            height: 37.22047424316406,
            child: GeneratedGroup9Widget1(),
          ),
          Positioned(
            left: 48.0,
            top: 757.0,
            right: null,
            bottom: null,
            width: 30.2312068939209,
            height: 41.357120513916016,
            child: GeneratedGroup10Widget1(),
          ),
          Positioned(
            left: 41.0,
            top: 537.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse26Widget(),
          ),
          Positioned(
            left: 62.04071044921875,
            top: 130.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget1(),
          ),
          Positioned(
            left: 31.0,
            top: 103.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedDevolta1Widget(),
          )
        ]),
      ),
    ));
  }
}
