import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedBateriacheia1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedSinalderede1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedV10Widget.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedLOADSTOPWidget.dart';
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/GeneratedWifi1Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/testeloadapp/generatedaberturawidget/generated/Generated1742Widget.dart';

/* Frame Abertura
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAberturaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedMapaWidget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: kIsWeb
              ? []
              : [
                  BoxShadow(
                    color: Color.fromARGB(63, 0, 0, 0),
                    offset: Offset(0.0, 4.0),
                    blurRadius: 4.0,
                  )
                ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 393.0,
            height: 852.0,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment(0.0, -1.0),
                end: Alignment(0.0, 0.9999999999999998),
                stops: [0.008477911353111267, 0.6689633131027222],
                colors: [
                  Color.fromARGB(0, 0, 0, 0),
                  Color.fromARGB(255, 0, 0, 0)
                ],
              ),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 1, 0, 87),
                    ),
                  ),
                  Positioned(
                    left: 74.0,
                    top: 502.0,
                    right: null,
                    bottom: null,
                    width: 250.0,
                    height: 66.0,
                    child: GeneratedLOADSTOPWidget(),
                  ),
                  Positioned(
                    left: 177.0,
                    top: 747.0,
                    right: null,
                    bottom: null,
                    width: 105.0,
                    height: 27.0,
                    child: GeneratedV10Widget(),
                  ),
                  Positioned(
                    left: 336.0,
                    top: 14.0,
                    right: null,
                    bottom: null,
                    width: 29.0,
                    height: 29.0,
                    child: GeneratedBateriacheia1Widget(),
                  ),
                  Positioned(
                    left: 287.0,
                    top: 16.0,
                    right: null,
                    bottom: null,
                    width: 24.0,
                    height: 24.0,
                    child: GeneratedWifi1Widget(),
                  ),
                  Positioned(
                    left: 28.0,
                    top: 20.0,
                    right: null,
                    bottom: null,
                    width: 43.0,
                    height: 22.0,
                    child: Generated1742Widget(),
                  ),
                  Positioned(
                    left: 86.0,
                    top: 16.0,
                    right: null,
                    bottom: null,
                    width: 21.0,
                    height: 21.0,
                    child: GeneratedSinalderede1Widget(),
                  ),
                  Positioned(
                    left: 120.0,
                    top: 229.0,
                    right: null,
                    bottom: null,
                    width: 152.0926513671875,
                    height: 196.6216278076172,
                    child: GeneratedGroup9Widget(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
