import 'package:flutter/material.dart';

/* Rectangle -my-location_90138 1
    Autogenerated by FlutLab FTF Generator
  */
class Generatedmylocation_901381Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 512.0,
        height: 512.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/fa5ac23e5c9405f4f77e99757d3a3e93960b6abc.png",
            color: null,
            fit: BoxFit.cover,
            width: 512.0,
            height: 512.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
