import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc2Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc12Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc9Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedEllipse27Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedSinalderede1Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc3Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc10Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc13Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedEllipse31Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc7Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedBasemapimageWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedMais1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc5Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedEllipse32Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedBateriacheia1Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc8Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc6Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedLoc4Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedWifi1Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/Generated1742Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedMenos1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedmapawidget/generated/GeneratedGroup6Widget.dart';

/* Frame Mapa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.008477911353111267, 0.6689633131027222],
            colors: [Color.fromARGB(0, 0, 0, 0), Color.fromARGB(255, 0, 0, 0)],
          ),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 852.0,
            child: GeneratedBasemapimageWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle11Widget(),
          ),
          Positioned(
            left: 236.0,
            top: 328.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc1Widget(),
          ),
          Positioned(
            left: 68.0,
            top: 565.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc4Widget(),
          ),
          Positioned(
            left: 197.0,
            top: 396.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc2Widget(),
          ),
          Positioned(
            left: 139.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc11Widget(),
          ),
          Positioned(
            left: 87.0,
            top: 711.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc12Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 281.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc7Widget(),
          ),
          Positioned(
            left: 268.0,
            top: 432.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc3Widget(),
          ),
          Positioned(
            left: 107.0,
            top: 227.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc8Widget(),
          ),
          Positioned(
            left: 341.0,
            top: 234.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc5Widget(),
          ),
          Positioned(
            left: 336.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc10Widget(),
          ),
          Positioned(
            left: 63.0,
            top: 373.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc9Widget(),
          ),
          Positioned(
            left: 224.0,
            top: 581.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc6Widget(),
          ),
          Positioned(
            left: 208.0,
            top: 711.0,
            right: null,
            bottom: null,
            width: 31.839601516723633,
            height: 47.0,
            child: GeneratedLoc13Widget(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget2(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget2(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget2(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget2(),
          ),
          Positioned(
            left: 24.0,
            top: 103.0,
            right: null,
            bottom: null,
            width: 68.0,
            height: 68.0,
            child: GeneratedEllipse27Widget(),
          ),
          Positioned(
            left: 42.0,
            top: 125.0,
            right: null,
            bottom: null,
            width: 32.45000076293945,
            height: 24.557373046875,
            child: GeneratedGroup6Widget(),
          ),
          Positioned(
            left: 324.0,
            top: 116.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 43.0,
            child: GeneratedGroup12Widget(),
          ),
          Positioned(
            left: 326.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 52.0,
            child: GeneratedGroup14Widget(),
          ),
          Positioned(
            left: 326.0,
            top: 686.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 85.0,
            child: GeneratedGroup15Widget(),
          ),
          Positioned(
            left: 326.0,
            top: 729.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 3.0,
            child: GeneratedLine12Widget(),
          ),
          Positioned(
            left: 341.0,
            top: 694.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: GeneratedMais1Widget(),
          ),
          Positioned(
            left: 341.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 22.0,
            child: GeneratedMenos1Widget(),
          ),
          Positioned(
            left: 264.0138244628906,
            top: 398.93267822265625,
            right: null,
            bottom: null,
            width: 23.31983184814453,
            height: 23.31983184814453,
            child: GeneratedEllipse32Widget(),
          ),
          Positioned(
            left: 269.0,
            top: 381.0,
            right: null,
            bottom: null,
            width: 18.0,
            height: 18.0,
            child: GeneratedEllipse31Widget(),
          )
        ]),
      ),
    ));
  }
}
