import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedSinalderede1Widget8.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedBateriacheia1Widget8.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedWifi1Widget8.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedSelecioneseuveculoWidget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedPreenchimentodevagoesdevistafrontal11Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedSinaldesetaparabaixoparanavegar11Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedRectangle32Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/Generated1742Widget8.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedMarcaWidget3.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedRectangle26Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedcarwidget2/generated/GeneratedSetadireita1Widget3.dart';

/* Frame Car 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 328.0,
            child: GeneratedRectangle24Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 83.0,
            child: GeneratedRectangle26Widget3(),
          ),
          Positioned(
            left: 0.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 68.0,
            child: GeneratedRectangle32Widget3(),
          ),
          Positioned(
            left: 35.0,
            top: 503.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 32.0,
            child: GeneratedMarcaWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 89.0,
            child: GeneratedRectangle31Widget2(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget8(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget8(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget8(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget8(),
          ),
          Positioned(
            left: 47.0406494140625,
            top: 79.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget3(),
          ),
          Positioned(
            left: 25.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 39.0,
            child: GeneratedPreenchimentodevagoesdevistafrontal11Widget2(),
          ),
          Positioned(
            left: 75.0,
            top: 426.0,
            right: null,
            bottom: null,
            width: 200.0,
            height: 29.0,
            child: GeneratedSelecioneseuveculoWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: 557.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 1.0,
            child: GeneratedLine7Widget1(),
          ),
          Positioned(
            left: 335.43157958984375,
            top: 501.83856201171875,
            right: null,
            bottom: null,
            width: 32.0,
            height: 32.0,
            child: GeneratedSinaldesetaparabaixoparanavegar11Widget3(),
          )
        ]),
      ),
    ));
  }
}
