import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedGoogle1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedBasemapimageWidget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedSinalderede1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedSenhaWidget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/Generated1742Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedBateriacheia1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedWifi1Widget1.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedLine11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedSetadireita2Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedEntrecomgoogleWidget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/testeloadapp/generatedloginwidget/generated/GeneratedFrame1Widget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.008477911353111267, 0.6689633131027222],
            colors: [Color.fromARGB(0, 0, 0, 0), Color.fromARGB(255, 0, 0, 0)],
          ),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 1, 0, 87),
            ),
          ),
          Positioned(
            left: -65.0,
            top: 1179.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 600.0,
            child: GeneratedBasemapimageWidget(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget1(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget1(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget1(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget1(),
          ),
          Positioned(
            left: 28.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 337.0,
            height: 467.0,
            child: GeneratedRectangle38Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 144.0,
            right: null,
            bottom: null,
            width: 266.0,
            height: 72.0,
            child: GeneratedGroup11Widget(),
          ),
          Positioned(
            left: 64.0,
            top: 251.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 28.0,
            child: GeneratedEmailWidget(),
          ),
          Positioned(
            left: 60.0,
            top: 342.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 28.0,
            child: GeneratedSenhaWidget(),
          ),
          Positioned(
            left: 88.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 211.0,
            height: 38.0,
            child: GeneratedRectangle46Widget(),
          ),
          Positioned(
            left: 153.0,
            top: 434.0,
            right: null,
            bottom: null,
            width: 81.0,
            height: 40.0,
            child: GeneratedFrame1Widget(),
          ),
          Positioned(
            left: 66.0,
            top: 300.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 1.0,
            child: GeneratedLine10Widget(),
          ),
          Positioned(
            left: 66.0,
            top: 396.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 1.0,
            child: GeneratedLine11Widget(),
          ),
          Positioned(
            left: 100.0,
            top: 526.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: GeneratedGoogle1Widget(),
          ),
          Positioned(
            left: 147.0,
            top: 531.0,
            right: null,
            bottom: null,
            width: 140.0,
            height: 22.0,
            child: GeneratedEntrecomgoogleWidget(),
          ),
          Positioned(
            left: 72.0406494140625,
            top: 110.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita2Widget(),
          )
        ]),
      ),
    ));
  }
}
