import 'package:flutter/material.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedSetadireita1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedBateriacheia1Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedCharger1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedShoppingBoaVistaWidget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedDisponvelWidget1.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedP7Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse24Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedGooglemaps1Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/Generated1742Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedCharger4Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedCharger3Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedDisponvelWidget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedWifi1Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedCharger2Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedSinalderede1Widget3.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedManutenoWidget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRdoGiriquiti48BoaVistaRecifePEWidget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/testeloadapp/generatedpontowidget/generated/GeneratedEmusoWidget.dart';

/* Frame Ponto
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPontoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 64.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 299.0,
            child: GeneratedRectangle12Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 337.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 80.0,
            child: GeneratedRectangle13Widget(),
          ),
          Positioned(
            left: 71.0,
            top: 354.0,
            right: null,
            bottom: null,
            width: 199.0,
            height: 29.0,
            child: GeneratedShoppingBoaVistaWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 64.0,
            child: GeneratedRectangle14Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 417.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 84.0,
            child: GeneratedRectangle15Widget(),
          ),
          Positioned(
            left: 56.0,
            top: 441.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 36.0,
            child: GeneratedEllipse8Widget(),
          ),
          Positioned(
            left: 56.0,
            top: 441.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 36.0,
            child: GeneratedEllipse11Widget(),
          ),
          Positioned(
            left: 11.0,
            top: 354.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 45.0,
            child: GeneratedRectangle16Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 503.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 72.0,
            child: GeneratedRectangle17Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 575.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 72.0,
            child: GeneratedRectangle18Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 72.0,
            child: GeneratedRectangle19Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 719.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 72.0,
            child: GeneratedRectangle20Widget(),
          ),
          Positioned(
            left: 26.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 29.0,
            child: GeneratedCharger1Widget(),
          ),
          Positioned(
            left: 26.0,
            top: 597.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 29.0,
            child: GeneratedCharger2Widget(),
          ),
          Positioned(
            left: 26.0,
            top: 662.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 29.0,
            child: GeneratedCharger3Widget(),
          ),
          Positioned(
            left: 26.0,
            top: 734.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 29.0,
            child: GeneratedCharger4Widget(),
          ),
          Positioned(
            left: 18.0,
            top: 363.0,
            right: null,
            bottom: null,
            width: 36.0,
            height: 32.0,
            child: GeneratedP7Widget(),
          ),
          Positioned(
            left: 71.0,
            top: 384.0,
            right: null,
            bottom: null,
            width: 219.0,
            height: 17.0,
            child: GeneratedRdoGiriquiti48BoaVistaRecifePEWidget(),
          ),
          Positioned(
            left: 336.0,
            top: 14.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 29.0,
            child: GeneratedBateriacheia1Widget3(),
          ),
          Positioned(
            left: 287.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedWifi1Widget3(),
          ),
          Positioned(
            left: 28.0,
            top: 20.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 22.0,
            child: Generated1742Widget3(),
          ),
          Positioned(
            left: 86.0,
            top: 16.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 21.0,
            child: GeneratedSinalderede1Widget3(),
          ),
          Positioned(
            left: 202.0,
            top: 528.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse22Widget(),
          ),
          Positioned(
            left: 202.0,
            top: 736.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse25Widget(),
          ),
          Positioned(
            left: 202.0,
            top: 599.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse23Widget(),
          ),
          Positioned(
            left: 202.0,
            top: 664.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse24Widget(),
          ),
          Positioned(
            left: 245.0,
            top: 529.0,
            right: null,
            bottom: null,
            width: 89.0,
            height: 24.0,
            child: GeneratedDisponvelWidget(),
          ),
          Positioned(
            left: 245.0,
            top: 737.0,
            right: null,
            bottom: null,
            width: 89.0,
            height: 24.0,
            child: GeneratedDisponvelWidget1(),
          ),
          Positioned(
            left: 245.0,
            top: 601.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 21.0,
            child: GeneratedEmusoWidget(),
          ),
          Positioned(
            left: 245.0,
            top: 666.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 24.0,
            child: GeneratedManutenoWidget(),
          ),
          Positioned(
            left: 274.0,
            top: 428.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: GeneratedGooglemaps1Widget(),
          ),
          Positioned(
            left: 46.0406494140625,
            top: 104.7674560546875,
            right: null,
            bottom: null,
            width: 24.76896858215332,
            height: 24.76896858215332,
            child: GeneratedSetadireita1Widget(),
          )
        ]),
      ),
    ));
  }
}
